server:
  port: 9999

spring:
  application:
    name: composition-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    ip-address: 192.168.1.37
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.86:8761/eureka


jwt:
  secret: example_token
  expire-length: 8640000